tlw = {
	'AA':'noun (-s)|rough, cindery lava',
	'AB':'noun (-s)|an abdominal muscle',
	'AD':'noun (-s)|an advertisement',
	'AE':'adjective|one',
	'AG':'adjective|pertaining to agriculture',
	'AH':'interjection|used to express delight, relief, or contempt',
	'AI':'noun (-s)|a three-toed sloth',
	'AL':'noun (-s)|an East Indian tree',
	'AM':'verb|present 1st person singular of BE',
	'AN':'indefinite article|used before words beginning with a vowel',
	'AR':'noun (-s)|the letter R',
	'AS':'adverb|to the same degree',
	'AT':'preposition|in the position of',
	'AW':'interjection|used to express protest, disgust, or disbelief',
	'AX':'verb (–ed, -ing, -es)|to work on with an ax (a type of cutting tool)',
	'AY':'noun (pl. –s)|aye',
	'BA':'noun (pl. –s)|the eternal soul in Egyptian mythology',
	'BE':'verb|to have actuality',
	'BI':'noun (-s)|bisexual',
	'BO':'noun (-s)|a pal',
	'BY':'noun (-s)|a pass in certain card games',
	'DE':'preposition|of; from – used in names',
	'DO':'noun (-s)|the first tone of the diatonic scale',
	'ED':'noun (-s)|education',
	'EF':'noun (-s)|the letter F',
	'EH':'interjection|used to express doubt',
	'EL':'noun (-s)|an elevated railroad or train',
	'EM':'noun (-s)|the letter M',
	'EN':'noun (-s)|the letter M',
	'ER':'interjection|used to express hesitation',
	'ES':'noun (-es)|the letter S (also spelled ESS)',
	'ET':'verb|a past tense of eat',
	'EX':'noun (-es)|the letter X',
	'FA':'noun (-s)|the fourth tone of the diatonic musical scale',
	'FE':'noun (-s)|a Hebrew letter',
	'GO':'verb|to move along',
	'HA':'noun (-s)|a sound of surprise',
	'HE':'noun (-s)|a male person',
	'HI':'interjection|used as a greeting',
	'HM':'interjection|used to express thoughtful consideration',
	'HO':'interjection|used to express surprise',
	'ID':'noun (-s)|a part of the psyche',
	'IF':'noun (-s)|a possibility',
	'IN':'verb|to harvest',
	'IS':'verb|present 3d person singular of be',
	'IT':'pronoun|the 3rd person singular',
	'JO':'noun (-es)|a sweetheart',
	'KA':'noun (-s)|the spiritual self of a human being in Egyptian religion',
	'KI':'noun (-s)|the vital force in Chinese thought',
	'LA':'noun (-s)|the sixth tone of the diatonic musical scale',
	'LI':'noun (-s)|a Chinese unit of distance',
	'LO':'interjection|used to attract attention or to express surprise',
	'MA':'noun (-s)|mother',
	'ME':'pronoun|the objective case of the pronoun I',
	'MM':'interjection|used to express assent or satisfaction',
	'MO':'noun (-s)|a moment',
	'MU':'noun (-s)|a Greek letter',
	'MI':'noun (-s)|the third tone of the diatonic musical scale',
	'MY':'pronoun|the possessive form of the pronoun I',
	'NA':'adverb|no; not',
	'NE':'adjective|born with the name of (also nee)',
	'NO':'noun (-s -es)|a negative reply',
	'NU':'noun (-s)|a Greek letter',
	'OD':'noun (-s)|a hypothetical force of natural power',
	'OE':'noun (-s)|a whirlwind off the Faeroe Islands',
	'OF':'preposition|coming from',
	'OH':'verb|to exclaim in surprise, pain, or desire',
	'OI':'verb|used to express dismay or pain',
	'OM':'noun (-s)|a mantra used in contemplation of ultimate reality',
	'ON':'noun (-s)|the side of the wicket where a batsman stands in cricket',
	'OP':'noun (-s)|a style of abstract art',
	'OR':'noun (-s)|the heraldic color gold',
	'OS':'noun (-s)|either an orifice, a bone, or an esker',
	'OW':'interjection|used to express sudden pain',
	'OX':'noun (-en -es)|a hoofed mammal or clumsy person',
	'OY':'interjection|used to express dismay or pain',
	'PA':'noun (-s)|a father',
	'PE':'noun (-s)|a Hebrew letter',
	'PI':'verb|to jumble or disorder',
	'QI':'noun (-s)|the vital force that in Chinese thought is inherent in all things',
	'RE':'noun (-s)|the second tone of diatonic musical scale',
	'SH':'interjection|used to urge silence',
	'SI':'noun (-s)|ti',
	'SO':'noun (-s)|the fifth tone of the diatonic musical scale',
	'TA':'noun (-s) an expression of gratitude',
	'TO':'preposition|in the direction of',
	'TI':'noun (-s)|the seventh tone of the diatonic musical scale',
	'UH':'interjection|used to express hesitation',
	'UM':'interjection|used to express hesitation',
	'UN':'pronounoun (-s)|one',
	'UP':'verb|to raise',
	'US':'pronoun|the objective case of the pronoun we',
	'UT':'noun (-s)|the musical tone C in the French solmization system, now replaced by do',
	'WE':'pronoun|the 1st person plural pronoun',
	'WO':'noun (-s)|woe',
	'XI':'noun (-s)|a Greek letter',
	'XU':'noun|a monetary unit of Vietnam',
	'YA':'pronoun|you',
	'YE':'pronoun|you',
	'YO':'interjection|used to call attention or express affirmation',
	'ZA':'noun (-s)|a pizza'
}
letters={
  'A':1,
  'B':3,
  'C':3,
  'D':2,
  'E':1,
  'F':4,
  'G':2,
  'H':4,
  'I':1,
  'J':8,
  'K':5,
  'L':1,
  'M':3,
  'N':1,
  'O':1,
  'P':3,
  'Q':10,
  'R':1,
  'S':1,
  'T':1,
  'U':1,
  'V':4,
  'W':4,
  'X':8,
  'Y':4,
  'Z':10
}